const DASHBOARD_ACTIONS = {
  SET_RECIPES: "SET_RECIPES",
  SET_SEARCH: "SET_SEARCH",
  SET_CATEGORY_FILTER: "SET_CATEGORY_FILTER",
  SET_NO_RECIPES_FOUND: "SET_NO_RECIPES_FOUND",
  CLEAR_FILTERS: "CLEAR_FILTERS",
};

export default DASHBOARD_ACTIONS;
